#!/usr/bin/env bash
cd $HOME/.config/i3
echo $image
sh wallpaper/switch_background 
echo "set background"
image=$(cat theme_info.temp | grep -oP 'name: \K.*')
if [ "$image" == "" ]; then
	echo "error image not set"
	feh --bg-scale "wallpaper/active/$(cat theme_info | grep -oP 'name: \K.*')"
	exit
fi
sh wallpaper/analyse -f "active/$image" -i 40 -c 4 -s >> theme_info.temp 
echo "analysed wallpaper"
sed -i 's/colour0\: /text = /' theme_info.temp
sed -i 's/colour1\: /background = /' theme_info.temp
sed -i 's/colour2\: /background_comp = /' theme_info.temp
sed -i 's/colour3\: /accent = /' theme_info.temp
cp theme_info.temp theme_info
rm theme_info.temp
echo "[colors]" > polybar/colours
cat theme_info | tail -n+2 >> polybar/colours
#merge poly config
cd polybar
cp colours config
cat config_template >> config
