#!/bin/bash
lemonbar -B "#11FFFFFF" -p -b -g 1920x25+1920+0 -o -7 -f '-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1' -o 0 -f '-misc-dejavu sans mono-medium-r-normal--0-0-0-0-m-0-iso10646-1'
 
