#!/bin/sh
sh $HOME/.config/i3/lemonbar/feeder | lemonbar -p -b -g 1920x25+1920+0 -o -7 -f '-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1' -o 0 -f '-misc-dejavu sans-medium-r-normal--0-0-0-0-p-0-iso10646-1'
 
