#!/bin/bash


BATT_EMPTY=$(echo -e '\ue236')
BATT_HALF=$(echo -e '\ue237')
BATT_FULL=$(echo -e '\ue238')
BATT_CHARGE=$(echo -e '\ue23a')
BATT_FULL_CHARGE=$(echo -e '\ue239')

GetDate() {
 	DATE=$(date "+%{F#669966}%Y/%m/%d | %{F#ff00ff}%_H:%M:%S")
	echo -n "$DATE"
}

while true; do
	echo "%{c} -$BATT_FULL_CHARGE- %{r}$(GetDate) "
	sleep 1
done
