#!/bin/bash

getCol() {
	col=$(cat theme_info | grep -oP "colour$1: \K.*")
	echo "$col"
}	

cd $I3_HOME


COL_MAIN_1=$(getCol 0)
COL_MAIN_2=$(getCol 1)
COL_SECOND=$(getCol 2)
COL_THIRD=$(getCol 3)
COL_SUPPORTING=$(getCol 4)

BATT_EMPTY=$(echo -e '\ue236')
BATT_HALF=$(echo -e '\ue237')
BATT_FULL=$(echo -e '\ue238')
BATT_CHARGE=$(echo -e '\ue23a')
BATT_FULL_CHARGE=$(echo -e '\ue239')

GetDate() {
 	DATE=$(date "+%{F$COL_MAIN_1}%Y/%m/%d %{F$COL_THIRD} | %{F$COL_MAIN_1}%_H:%M:%S")
	echo -n "$DATE"
}

while true; do
	echo "%{c} -$BATT_FULL_CHARGE- %{r}$(GetDate) "
	sleep 1
done
