#!/bin/bash
COLOURS="6"
MIN_INTENSITY="50"
getDec() {
	echo $(echo "$((16#$1))")
}
analyse() {
	echo "Analysing image $1"
	NUM=0
	convert "$1" -format %c -depth 3 histogram:info:- | sort -r -t: -nk 1 | grep -oE "#[0-9A-F]{6}" | while read line; do
		echo "$line"
		R=$(getDec $(expr substr $line 2 2))
		G=$(getDec $(expr substr $line 4 2))
		B=$(getDec $(expr substr $line 6 2))
		INTENSITY=$((($R + $B + $G)/3))
		if [ $INTENSITY -lt $MIN_INTENSITY ]; then
			continue
		fi
		echo "$INTENSITY"		
		convert colours.png -fill $line -draw "point $2,$NUM" colours.png
		NUM=$(($NUM+1))
		if [ "$NUM" = "$COLOURS" ]; then
			break
		fi
	done
}


cd "$I3_HOME/wallpaper"
if [ ! "$1" = "" ]; then
	IMAGE=$1
else
	echo "usage analyseImage <file/dir>" 
	exit;
fi
convert -size "$(ls -1 $IMAGE | wc -l)x$COLOURS" xc:black -stroke none colours.png
if [ -d "$1" ]; then 
	X=0
	ls $1 | while read line; do
		analyse "$1/$line" $X
		X=$(($X+1))
	done
fi
if [ -f "$1" ]; then
	analyse $IMAGE 0
fi
convert colours.png -filter point -resize 16000% colours.png
