#!/bin/bash
OUTPUT=false

while getopts 'of:' arg; do
	case "${arg}" in
		o) OUTPUT=true ;;
		f) FILE="${OPTARG}" ;;
		*) error "Unexpected option $arg" ;;
	esac	
done

echo $OUTPUT
echo $FILE

if [ "$FILE" = "" ]; then
	echo "Error: No input file"
fi
COLOURS="6"
MIN_INTENSITY="30"

getDec() {
	echo $(echo "$((16#$1))")
}
analyse() {
	echo "Analysing image $1"
	NUM=0
	convert "$1" -format %c -depth 4 histogram:info:- | sort -r -t: -nk 1 | grep -oE "#[0-9A-F]{6}" | while read line; do
		echo "$line"
		R=$(getDec $(expr substr $line 2 2))
		G=$(getDec $(expr substr $line 4 2))
		B=$(getDec $(expr substr $line 6 2))
		INTENSITY=$((($R + $B + $G)/3))
		if [ $INTENSITY -lt $MIN_INTENSITY ]; then
			continue
		fi
		echo "$INTENSITY"		
		convert colours.png -fill $line -draw "point $2,$NUM" colours.png
		NUM=$(($NUM+1))
		if [ "$NUM" = "$COLOURS" ]; then
			break
		fi
	done
}

cd "$I3_HOME/wallpaper"

convert -size "$(ls -1 $IMAGE | wc -l)x$COLOURS" xc:black -stroke none colours.png
if [ -d "$FILE" ]; then 
	X=0
	ls $FILE | while read line; do
		analyse "$FILE/$line" $X
		X=$(($X+1))
	done
fi

if [ -f "$FILE" ]; then
	analyse $FILE 0
fi
convert colours.png -filter point -resize 16000% colours.png
