#!/bin/bash
cd $HOME/.config/i3
sh wallpaper/switch_background 
sh wallpaper/analyse -f "active/$(cat theme_info.temp | grep -oP 'name: \K.*')" -i 40 -c 6 -s >> theme_info.temp
cat theme_info.temp > theme_info
rm theme_info.temp
