#!/bin/bash
cd $HOME/.config/i3
sh wallpaper/switch_background
echo $(cat theme_info | grep -oP 'name: \K.*')
sh wallpaper/analyse -f "active/$(cat theme_info | grep -oP 'name: \K.*')" -i 40 -c 6 -s >> theme_info
