#!/bin/sh
#cd to this dir 
source $HOME/.bash_profile
DISPLAY=$(cat $HOME/.xenv) 
cd $HOME/.config/i3/wallpaper/
if [ "$(cat current)" = "" ]; then
	rm current
fi
if [ ! -f "current" ]; then
	ls active > temp 
	shuf -n 1 temp > current 
fi
#ls |  remove current | remove all non-image files | save in temp file
ls active |  grep -Ev "$(cat current)" | grep -E "*\.[jpg|png]" > temp
#select one random line and overwrite current
shuf -n 1 temp > current
#set as desktop background. First line needed for feh to recognise the X session 
DISPLAY=$(cat $HOME/.xenv) feh --bg-scale "active/$(cat current)"
#remove temp file 
rm temp
