#!/bin/sh
#cd to this dir 
source $HOME/.bash_profile
DISPLAY=$(cat $HOME/.xenv) 
cd $HOME/.config/i3
if [ ! -f "theme_info" ]; then 
	echo "name: $(ls wallpaper/active | shuf -n 1 -)" > theme_info
fi
#ls |  remove current | remove all non-image files | save in temp file
wallpaper=$(ls wallpaper/active |  grep -Ev "$(cat theme_info | grep -oP 'name: \K.')" | grep -E "*\.[jpg|png]" | shuf -n 1 -)
#select one random line and overwrite current
echo "name: $wallpaper" > theme_info
#set as desktop background. First line needed for feh to recognise the X session 
DISPLAY=$(cat $HOME/.xenv) feh --bg-scale "wallpaper/active/$wallpaper"

